# Generated by Django 2.0.2 on 2018-02-22 00:37

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '要点详情',
                'verbose_name': '要点详情',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='大纲')),
            ],
            options={
                'verbose_name_plural': '编程类别',
                'verbose_name': '编程类别',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(max_length=200, verbose_name='要点')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='关联大纲')),
            ],
            options={
                'verbose_name_plural': '知识要点',
                'verbose_name': '知识要点',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Point', verbose_name='关联要点'),
        ),
    ]
